### PR TITLE
Deleted 4.4 and 4.5 which just contained Readme files. Changed 4.6 to 4....

### PR DESCRIPTION
**Pull request by gomezc**
...5 to reflect new exercise ordering for Session 4.

### CODE REVIEW

**Comment by gomezc** [comment]
@jrgnicho please review... and merge?

**Comment by jrgnicho** [comment]
Are there launch files for exercise 4.5 in the work and orig directories or they are created as part of the exercise?

**Comment by gomezc** [comment]
The launch file is created at the end as an extra part of the exercise.

**Comment by jrgnicho** [comment]
+1

**Pull request merged**
