### PR TITLE
Descartes training exercises

### PR DESCRIPTION
**Pull request by jrgnicho**
This PR adds the descartes related exercises 4.1 to 4.3.  It should only be merged after PR #60 is accepted.  It may also have to be rebased.

### CODE REVIEW

**Comment by jrgnicho** [comment]
This branch has been rebased against **indigo-devel** in order to incorporate the latest changes.  It is ready for review.

**Comment by jrgnicho** [comment]
Not sure why rebasing didn't work, I'll fix the discrepancies.

**Comment by jrgnicho** [comment]
it looks like the moving of 4.1 -> 1.3 confused github.  The discrepancies have been addressed.

**Comment by jrgnicho** [comment]
The last commit removed the **required** attribute from the exercises' launch files

**Comment by gomezc** [comment]
+1

**Pull request merged**
