### PR TITLE
Converted demo 1 instructions to reStructuredText

### LINKED ISSUE #322: [Demo 1] Perception-driven manipulation "Robot model parameter not found"
Setup:
* Native Ubuntu 18.04 LTS install
* `.check_training_config.bash` result is all [OK]

I checked both the `template_ws` and the `solution_ws`, and both build fine, but I get the following (fatal) error(s) when directly after starting `roslaunch collision_avoidance_pick_and_place ur5_pick_and_place.launch`:

```
[ INFO] [1594218924.570461140]: Parameters successfully read
[ERROR] [1594218924.572215833]: Robot model parameter not found! Did you remap 'robot_description'?
[ERROR] [1594218924.577955019]: Robot model parameter not found! Did you remap 'robot_description'?
[FATAL] [1594218924.578414487]: Unable to construct robot model. Please make sure all needed information is on the parameter server.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to construct robot model. Please make sure all needed information is on the parameter server.
[ERROR] [1594218924.601495686]: Robot model not loaded
[ERROR] [1594218924.610968811]: Planning scene not configured
```

### PR DESCRIPTION
**Pull request by max-sn**
Includes:
* The instructions for demo 1 are converted to reStructuredText
* Instructions are added to fix #322. 
* For my build process I also added support for Sphinx versions >=1.4, this shouldn't break anything for lower versions.

### CODE REVIEW

**Comment by marip8** [comment]
I think this looks really good; thanks for putting this together. I have a few minor formatting changes that I would like to add before merging. Would you mind allowing edits by maintainers for this PR (should be a check-box on this page at the bottom right)? It's a little easier for me to push the commit directly on to this branch as opposed to opening a PR against your fork.

**Comment by max-sn** [comment]
I don't see such a checkbox on this page, could that be because I'm not formally the owner of the fork? (It says here that to enable that it should be a user-owned fork: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by marip8** [comment]
No problem. I've attached the commit as a patch below instead. You should be able to apply it to this branch by running the following command on your branch:

```bash
git am minor-formatting-changes.patch
```

[minor-formatting-changes.patch.zip](https://github.com/ros-industrial/industrial_training/files/4914528/minor-formatting-changes.patch.zip)

**Comment by max-sn** [comment]
That's a great feature! Thanks for the changes by the way, some things I noticed already but I was unsure whether I should change them, but other things I completely missed.

**Review by marip8 — APPROVED** [review]

**Comment by marip8** [comment]
Thanks for the contribution and documentation improvement

**Pull request merged**
