### PR TITLE
Add ros::spin(); to example code in Topics-and-Messages.md

### PR DESCRIPTION
**Pull request by roggedaniel**

### CODE REVIEW

**Comment by jdlangs** [comment]
Hi @roggedaniel, thanks for the PR. It's a bit confusing but that `main` function already has a `spin()` call in it from the way this exercise builds on the previous one. I think what would work better would be add another ellipsis below the `ROS_INFO` with a comment mentioning the (already-existing) spin. In general, it would be nice if any ellipsis in the examples had short notes describing what should be there already. Feel free to expand your PR along those lines if you want.

**Comment by roggedaniel** [comment]
Josh,

I noticed that after cutting and copying the example code and finding that it didn’t work.  I agree that the ellipses would be an acceptable route, and are more consistent with the other examples.  I’ll submit a new PR.

Rogge



Daniel Rogge
CEO

TORMACH INC.
1071 Uniek Dr
Waunakee, WI 53597-9588
T: (608) 850-2584
E: drogge@tormach.com
Tormach Office (608) 849-8381


www.tormach.com<http://www.tormach.com>
100% Employee Owned

[cid:template13_sm_fb_18d17647-954c-4110-871a-7113c8c0de9a11111.png]<https://www.facebook.com/Tormach/>  [cid:template13_sm_linkedin_5d790cd9-4767-49a2-bbb7-5bc1b350de8311111.png] <https://www.linkedin.com/company/tormach>   [cid:template13_sm_twitter_bbd37982-0cdf-4e18-9c44-2326e4c7fc8911111.png] <https://twitter.com/Tormach>   [cid:template13_sm_gplus_65eec46e-cf84-4df7-8757-ca8a2c600c3711111.png] <https://plus.google.com/+tormachllc>

[cid:tormachlogo_8bc55768-862c-4bcb-a197-d5074d516624.png]


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager.

**Comment by roggedaniel** [comment]
Josh,

Does this look OK to you?

int main(int argc, char** argv)
{
  ...
  // The Localizer class provides this node's ROS interfaces
  Localizer localizer(nh);

  ROS_INFO("Vision node starting");
  ... // Note: don't forget to leave ros::spin(); in place or this code will only run once.
}



Daniel Rogge
CEO

TORMACH INC.
1071 Uniek Dr
Waunakee, WI 53597-9588
T: (608) 850-2584
E: drogge@tormach.com
Tormach Office (608) 849-8381


www.tormach.com<http://www.tormach.com>
100% Employee Owned

[cid:template13_sm_fb_18d17647-954c-4110-871a-7113c8c0de9a11111.png]<https://www.facebook.com/Tormach/>  [cid:template13_sm_linkedin_5d790cd9-4767-49a2-bbb7-5bc1b350de8311111.png] <https://www.linkedin.com/company/tormach>   [cid:template13_sm_twitter_bbd37982-0cdf-4e18-9c44-2326e4c7fc8911111.png] <https://twitter.com/Tormach>   [cid:template13_sm_gplus_65eec46e-cf84-4df7-8757-ca8a2c600c3711111.png] <https://plus.google.com/+tormachllc>

[cid:tormachlogo_8bc55768-862c-4bcb-a197-d5074d516624.png]


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager.

**Comment by jdlangs** [comment]
Yep, that's fine with me, though I wouldn't mind dropping the "or this code..." to be succinct.

Also, when you update the PR, can you switch the base branch to `kinetic-devel` instead of `kinetic`? That's where all the most recent changes should go.

Thanks,
Josh

**Comment by jrgnicho** [comment]
The originating repo seems to have been deleted.

**Comment by jrgnicho** [comment]
#168  addresses this.

**Pull request closed without merging**
