### PR TITLE
Fixes for kinetic-devel decartes application demo

### PR DESCRIPTION
**Pull request by geoffreychiou**
Moved demo_descartes to demo_descartes_planning_and_execution + several changes to make the code build without any errors.

@austinderic

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Just a question: why do we keep copying packages into the `industrial_training` pkg instead of using something like `wstool` or `vcstool` to checkout specific versions from their repositories?

Copying entire stacks (like the `universal_robot` stack that was copied previously seems like a bad idea, so I'm curious what the rationale is?

**Comment by AustinDeric** [comment]
@gavanderhoorn Great point and I agree 1,000%.  The training team discussed using .rosinstall files with wstools.  The problem was that the class is already complicated enough and adding in things like wstools and .rosinstall was too complicated.

With that said i think we should look at incorporating wstools, .rosinstall and symbolic links into the training in the future.

universal_robot, is pre-loaded in the VM and it shouldn't be in this repo. There was some miscommunication on my part.  @geoffreychiou is currently fixing the problem.

**Comment by gavanderhoorn** [comment]
@AustinDeric wrote:
> The problem was that the class is already complicated enough and adding in things like wstools and .rosinstall was too complicated.

Wouldn't those just become part of the 'magic incantations' that the class is full of already? At least in my experience people just copy/paste whatever is there in the tutorial(s). One more command line would probably not make much difference.

Once trainees become comfortable enough with tooling they'll start asking about `wstool`, at which point you can decide whether or not to explain it.

**Comment by AustinDeric** [comment]
@gavanderhoorn the short answer is yes.  However, i am deferring to the people performing the training:  @Levi-Armstrong and @JeremyZoss .

**Comment by gavanderhoorn** [comment]
I was just thinking out loud, didn't mean to force you to make a decision (if any).

**Comment by AustinDeric** [comment]
Its a great point and hotly debated here.  Your comments and input are greatly appreciated.

**Comment by JeremyZoss** [comment]
Here is some historical context that may/not be relevant.  Originally, we copied 3rd-party packages into the training material for several reasons:
  1. Last-minute bug-fixes that hadn't made their way into any public repos
  1. Source code from public repos that contained fixes not present in binary packages
  1. These were transparently included, to hide dependencies from users when irrelevant to primary course content.
  1. Sometimes we give training with limited/no internet access.  Having all required files available locally is critical in these cases.

My intent was always to prefer using binary packages when available, and to phase out the "supplemental" packages when they were no longer needed.

I'll try to review the current set of supplemental packages, to see if they're still required.  I'm generally for minimizing the reliance on "magic incantations".  In some cases, we may be able to pre-install some of the supplemental packages in the VM image, separate from the actual course-material wiki (and provide instructions for users creating their own environment from scratch).

**Comment by Levi-Armstrong** [comment]
If I remember correctly, currently the on the Training VM the workspace is being extend to include the supplemental folder via the .bashrc file.  This could cause issues later for trainees that use this work for other projects. Would it be better to do a rosinstall of these supplemental packages?

**Comment by jrgnicho** [comment]
This has been included into PR #96

**Pull request closed without merging**
