### PR TITLE
Interactive bridge for Exercise 7.2 and minor corresponding compatibility changes for Exercise 4.1

### PR DESCRIPTION
**Pull request by KevinWarburton**
@jdlangs and @JeremyZoss . This is a Draft that Josh should probably evaluate first before Jeremy verifies that he his happy with the PR for training.

### CODE REVIEW

**Comment by jdlangs** [comment]
Overall the structure looks fine. Some details to address:
- The instructions don't tell the students what files to open and where to put the code blocks
- The code block still have comments about filling in code. It should be clarified for the student if something more is expected.

**Comment by JeremyZoss** [comment]
I assume that you've finished your planned updates, since you've removed the "Draft" title.  I haven't had a chance to review yet.  There's a lot of "small/busy" commits here, so we should probably squash at least some of them before merging to avoid cluttering the history.

I'm not sure of the reason behind some changes (introducing `ros2` into `exercises/4.1/ros1`, redefining `ARMarker`, removing vision node, etc), but maybe it'll become more clear once I've had a chance to work through the exercise.

**Comment by KevinWarburton** [comment]
@JeremyZoss , I am happy with the current PR's state, so there is no "Draft" in the title. However, I will address your request to squash commits:

- [x] I will squash the last 5 commits before @reidchristopher provided a PR on my fork with some typo fixes.

* To exemplify the `ros1_bridge`, the ROS2 code in `Exercise 7.2` requires services/topics advertised in ROS1 code from `Exercise 4.1`. The PR walks the student through creating separate ROS1 and ROS2 workspaces with these exercises.
  * The modified message `exercises/4.1/ros1/src/myworkcell_core/srv/LocalizePart.srv` should not break the 4.1 exercise according to @jdlangs . I can confirm that for you. I did this to make the service compatible with ROS2.
  * There is no ROS2 code inside `Exercise 4.1`. I assume you are referring to the file `exercises/4.1/ros1/src/myworkcell_support/launch/ros2_setup.launch`, which is designed to be used during `Exercise 7.2` and ignored during `Exercise 4.1`. This file existed before this PR. I edited it to improve compatibility with the new `Exercise 7.2`.
  * In the old `Exercise 7.2`, the `ARMarker` pose was hard-coded on the ROS2 side. I added functionality to communicate the `ARMarker` service advertised in `Exercise 4.1` to the ROS2 code in `Exercise 7.2`.

**Comment by JeremyZoss** [comment]
Merging this as-is so it can be potentially included in current training session.  But needs further discussion about how to streamline and better integrate this exercise into Basic Training course.  I recommend expanding ex4.1 rather than replacing the entire application/workspace.

Fails to build ros1_bridge in both a standalone VM and the AWS training image, with the same error (see below).  I will advise students not to attempt this exercise if the build errors can't be resolved.
```
/usr/bin/ld: libros1_bridge.so: undefined reference to `ros1_bridge::Factory<controller_manager_msgs::ControllerState_<std::allocator<void> >, controller_manager_msgs::msg::ControllerState_<std::allocator<void> > >::convert_1_to_2(controller_manager_msgs::ControllerState_<std::allocator<void> > const&, controller_manager_msgs::msg::ControllerState_<std::allocator<void> >&)'
/usr/bin/ld: libros1_bridge.so: undefined reference to `ros1_bridge::Factory<controller_manager_msgs::ControllerState_<std::allocator<void> >, controller_manager_msgs::msg::ControllerState_<std::allocator<void> > >::convert_2_to_1(controller_manager_msgs::msg::ControllerState_<std::allocator<void> > const&, controller_manager_msgs::ControllerState_<std::allocator<void> >&)'
```

**Comment by KevinWarburton** [comment]
@JeremyZoss , Thanks for finding the issue. The error you mention seems to be a bug in the bridge itself as reported in the `ros1_bridge` issue [#329](https://github.com/ros2/ros1_bridge/issues/329). The solution that closed the issue was to reinstall `foxy`. However, testing between @KevinWarburton , @reidchristopher , and @jrgnicho confirms that purging part of `ros2_control` enables the `ros1_bridge` to build from source successfully.

`sudo apt purge ros-foxy-controller-manager-msgs --autoremove`

You can reinstall after running the bridge for Exercise 7.2 with the following:

`sudo apt install ros-foxy-ros2-control`

Overall, this means you cannot build the bridge from source while having both `ros_control` for `noetic` and `ros2_control` for `foxy` installed. I will post a PR that reports the required workaround inside the documentation for Exercise 7.2.

**Pull request merged**
