### PR TITLE
[Perception-Driven_Manipulation] Fixed controller and compilation error. 

### PR DESCRIPTION
**Pull request by ngwk1**
1. Added `allowed_execution_duration_scaling` and `execution_duration_monitoring` to bypass controller time out error. User may scale the value to increase the buffer for controller time out error. 

2. Changed `Affine3d` to `Isometry3d` to skip compilation error.

### CODE REVIEW

**Comment by ngwk1** [comment]
#

**Comment by ngwk1** [comment]
3. Added additional parameters `hw_interface` to overcome compilation error.

**Comment by gavanderhoorn** [comment]
May I suggest to keep pull requests small and coherent? It would be good to submit one PR per set of related changes.

That way reviews are much simpler and reverting a PR is also facilitated.

**Comment by dejaniraai** [comment]
Closed to create a single PR request for this repository, with all the fixes included.

**Comment by gavanderhoorn** [comment]
@dejaniraai: the suggestion was actually to create separate PRs, not a single large one.

Is that what you intend to do?

**Comment by dejaniraai** [comment]
Yes, sorry,  the other way around. Creating multiple PR requests, one for each individual issue.

**Pull request closed without merging**
