### PR TITLE
Basic training in ROS2

### PR DESCRIPTION
**Pull request by jdlangs**
This is the first chunk of an ongoing port of the ROS basic training (sessions 1&2) material to ROS2. Right now it covers all the pages from ~~session 1~~ sessions 1 & 2. Right now, this new material is presented up front without reference to ROS1 and the previous ROS1 pages are now linked at the bottom of the page as `Legacy`.

<details>
<summary>Here is what it looks like.</summary>

ROS-Industrial-Training-Index

</details>

@marip8 @jrgnicho @JeremyZoss @Levi-Armstrong any feedback or suggestions would be greatly appreciated.

### CODE REVIEW

**Comment by JeremyZoss** [comment]
I didn't review the meat of the PR at all... definitely would be good to have someone else at least work through the steps and see if they make sense.  I assume there's a fairly significant revision to the "presentation" content (slides/PDF) as well?

My only real comment is regarding the main page "legacy" layout.  Personally, I think the page is getting kind of long and unwieldy.  I would prefer to see a statement near the top that reads something like: "We are in the process of updating much of our training content from ROS1 to ROS2.  To access older ROS1 topics or other deprecated content, please visit the [Legacy Training]() page.".  Then move whatever links you've currently got at the bottom to a separate page, instead.  This maybe also gives us flexibility to retire other unsupported / non-functional content.  Rather then keeping it on the main page or deleting it entirely.

**Comment by jdlangs** [comment]
@JeremyZoss good call about it starting to look too cluttered and unwieldy. I went ahead with the legacy page idea, and now the index page looks like [this](https://ibb.co/HXxc2QW). Let me know what you think.

**Comment by marip8** [comment]
For now is the port mostly just copy-pasting the old training and updating the text? If not I think there a number of small things we should do like re-organizing the demos in a meaningful way (rather than continuing the numbering scheme), re-titling the files so they are in chronological order in the directories (helps when editing pages later), reformatting to ReST, etc. I feel like that's probably out-of-scope here, but I wanted to put it out there in case it's not

**Comment by jdlangs** [comment]
I think a full reformat to ReST is out of scope for now, but the other stuff should be simple enough. Can you clarify your comment about 're-organizing the demos'? Are they not already distinct from the exercise page numbers?

**Comment by marip8** [comment]
What I meant by re-organizing actually pertains as much to the advanced material as to the demos. On the markdown pages the demos/exercises are referred to by number, like 5.1 (Advanced Descartes), 5.2 (Perception Pipeline), ..., 7.2 (ROS 1/2 Bridge), but they don't necessarily need to be done in any particular order because they are more-or-less stand-alone. I think we should re-organize them by category (i.e. Motion Planning, Perception, Code Quality (documentation, unit testing, etc.), Demos) and label them by topic instead of number. Maybe it would be possible to make this into a sub-folder structure like:

```
|-- Core
     |-- Session 1
     |-- Session 2
     |-- ...
|-- Advanced Material
     |-- Motion Planning
         |-- Topic A
         |-- Topic B
     |-- Perception
         |-- Topic A
         |-- Topic B
     |-- ...
|-- Demos
     |-- Demo A
     |-- Demo B
|-- Legacy
    |-- Core
    |-- ...
```

I'm not sure how difficult this would be to implement, but it seems like it would make the training material easier to navigate and understand

**Comment by jdlangs** [comment]
Ok, I see what you mean. Doing a full reorganization like that is probably best done with another PR, maybe after gathering a few more opinions in an issue. For here I can include the numbering in the file names at least though.

**Comment by jdlangs** [comment]
This now includes the ROS2 exercise solutions for sessions 1 & 2. The only major thing left is slides, which are not yet ready for uploading. I also had a thought that it may be simpler and easy to maintain if we associate a handful of slides with each exercise, rather that large decks that go with each session. Any thoughts?

I've also created another (temporary) read-the-docs project that builds this branch: https://industrial-training-dev.readthedocs.io/en/latest/ Take a look if you'd like to explore the pages more carefully. We'll probably work with this page during the training this week and then I can do another round of cleanup before this finally gets merged.

**Comment by jdlangs** [comment]
Did a quick update and updated everything for Foxy. No real difference as far as the API.

**Comment by JeremyZoss** [comment]
Looks good to me.  Had just a few minor edits, but ran fine on a fresh 20.04/foxy install.  Checked all of Session 1-2.  Some updates will need to be carried through into exercises for sessions 3/4.

Other things I noted but haven't fixed yet:
- PC Setup recommends using a VM for training, but we haven't released a focal/noetic/foxy VM yet
- Some packages are requested by setup/check scripts, but are not yet released as debian packages in noetic
    - `industrial_core`, `openni_launch`, `openni_camera`, `openni2_launch`, `openni2_camera`
- Exercise 2.2 says that `output="screen"` argument is required to see INFO messages in console.  In my testing, launch files echoed INFO messages to console even without this argument
- Consider adding more explicit references to ROS1/2 equivalent commands.  Maybe this is best sprinkled throughout the exercises, or maybe it would be helpful to include a reference "cheatsheet" somewhere.  Listing both command-line equivalents and common code fragments.

Overall, it looks good and we should merge this as-is.

**Comment by jdlangs** [comment]
@JeremyZoss, sorry I somehow missed your comment. Thanks for the detailed check and review. I'll merge this now and keep those points in mind going forward.

**Pull request merged**
