### PR TITLE
Minor typo correction in doc

### PR DESCRIPTION
**Pull request by racheltrimble**

### CODE REVIEW

**Review by jdlangs — APPROVED** [review]

**Review by DavidMerzJr — APPROVED** [review]
Good catch.

**Comment by DavidMerzJr** [comment]
It looks like CI has hung on this one.  I'm going to pull down and manually merge.

**Comment by DavidMerzJr** [comment]
@marip8 I tried manually merging, but `melodic` (probably wisely) is push-protected.  Do you know how to restart (or override) CI so that this very sensible typo fix can be merged?  I realize that we don't use `melodic` any more, but someone else did go to the trouble of fixing it for us.

**Comment by marip8** [comment]
I just removed the requirement to have CI pass on the melodic branch

**Comment by marip8** [comment]
@racheltrimble thanks for the contribution

**Comment by racheltrimble** [comment]
Thanks all!

**Pull request merged**
