### PR TITLE
Update from indigo-devel

### PR DESCRIPTION
**Pull request by jrgnicho**
Consolidate all changes made to the indigo-devel branch before the deletion of all "-devel" branches.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Would it be an idea to create some tags at the commits that are currently `HEAD` on the various branches? That way going back to an earlier version is more convenient than having to figure out a hash and check that out directly.

**Comment by jrgnicho** [comment]
@gavanderhoorn that's a good idea, are there any example/templates that you may know about?

**Comment by gavanderhoorn** [comment]
I'm not sure what you're asking?

Easiest is probably to just checkout each individual branch and do a `git tag -am "$name" $name` (where `$name` is a name you make up, perhaps name of the ROS distro that specific version of the training docs targeted).

**Comment by jrgnicho** [comment]
I'm not too familiar with tagging commits as you just described and so I thought you meant recording the version in a commit message.  
Either way, creating tags as in your example should do the job.

**Pull request merged**
