### PR TITLE
Perception-Driven_Manipulation demo fixes

### PR DESCRIPTION
**Pull request by AustinDeric**
- solution_ws tested and working on hardware (needs better calibration)
- template_ws untested on hardware and not 100% complete with respect to the wiki.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I noticed there are a lot of `*Action*.msg` files in this PR ([object_manipulation_msgs/msg/FindContainerActionFeedback.msg](https://github.com/AustinDeric/industrial_training/blob/8301c393b8b0d5f04d9bc0a8ff26f2573368b781/exercises/Perception-Driven_Manipulation/solution_ws/src/object_manipulation_msgs/msg/FindContainerActionFeedback.msg) fi). As these are autogenerated during build, where do they / did they come from?

**Comment by AustinDeric** [comment]
Due to time constraints, I copied this object_manipulation_msgs package from the indigo branch.  I believe the messages come from: <https://github.com/ros-interactive-manipulation/object_manipulation/object_manipulation_msgs>.

**Comment by gavanderhoorn** [comment]
Looking in [object_manipulation_msgs/msg](https://github.com/ros-interactive-manipulation/object_manipulation/tree/groovy-devel/object_manipulation_msgs/msg) I don't see any of those autogenerated messages.

**Comment by Levi-Armstrong** [comment]
I have logged an issue #103.

**Pull request merged**
