### PR TITLE
includes ur5 xacro from the ur_description package

### PR DESCRIPTION
**Pull request by jrgnicho**
This change fixes an error with the perception driven manipulation demo application

### CODE REVIEW

**Review by marip8 — CHANGES_REQUESTED** [review]
@jrgnicho we should resolve this per discussion in #279 (make the demo use the UR URDF from the `ur_description` package instead)

**Comment by jrgnicho** [comment]
@marip8 agreed, however in the mean time we should either merge this PR or #279 because the demo is currently broken

**Comment by marip8** [comment]
@jrgnicho can you amend this PR to remove the custom UR5 URDF from the exercise and update the places where it is called to use the `ur_description` package? The UR repository is already in the `.rosinstall` file, so it should be a straightforward replacement

**Comment by gavanderhoorn** [comment]
> The UR repository is already in the `.rosinstall` file, so it should be a straightforward replacement

To avoid this sort of breakage in the future, perhaps you could configure a specific commit with the `version` key instead of tracking a branch (if you really want to build from source, that is).

**Comment by marip8** [comment]
We still need to build the UR repository from source for melodic. We should be able to grab the latest commit from the `kinetic-devel` branch for the `.rosinstall` and have everything work. We should also probably create ROS launch tests for each demo just to ensure they at least start up correctly, but that can be addressed outside this PR

**Comment by gavanderhoorn** [comment]
> We still need to build the UR repository from source for melodic. 

not necessarily.

You could add the output of `rosinstall_generator --tar --rosdistro=kinetic ur_description` to your `.rosinstall` file instead of the stanza you have there now.

That would download the currently released version (in Kinetic) as a tarbal into your workspace. You would be building from source, but only that package and as it's a released version, you're not tracking any moving targets.

> We should also probably create ROS launch tests for each demo just to ensure they at least start up correctly, but that can be addressed outside this PR

A `roslaunch_add_file_check(..)` would probably already have discovered this btw, as the `.xacro` will refuse to load.

**Comment by jrgnicho** [comment]
@marip8 I haven't run the demos with the latest UR urdf from the official `ur_description` package so there's a chance that the demo may fail if we switch to the urdf from that package.  Ideally, we'd switch to the urdf in the new [Universal Repo](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) as it also contains the drivers that work on more recent controller versions that the ur_modern_driver does not support.

**Comment by gavanderhoorn** [comment]
>  Ideally, we'd switch to the urdf in the new [Universal Repo](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) as it also contains the drivers that work on more recent controller versions

That repository does not contain any support packages. Only a driver.

The instructions do tell you to clone a fork of `universal_robot`, but that's a temporary situation until we get the necessary changes merged into the upstream repository.

If you're not interested in using the kinematic calibration data from the controller, you also don't need to use the fork IIRC.

**Comment by marip8** [comment]
Closing; addressed by #315

**Pull request closed without merging**
