### PR TITLE
WIP: Update 1-Workcell-XACRO.md

### PR DESCRIPTION
**Pull request by DavidMerzJr**
Fixes to various common areas encountered during the training.

### CODE REVIEW

**Comment by DavidMerzJr** [comment]
Please don't merge until after the training.

**Comment by DavidMerzJr** [comment]
We also need to update the ROS2 solution for exercise 3.3, as the controllers.yaml has not been updated from its ROS1 format.

**Comment by jdlangs** [comment]
I don't believe it should be part of the exercise contents to check for and install dependencies. Ideally these packages should be in a list for either the automated setup or configuration check scripts to use.

It may be useful to explicitly label a *Dependencies* section in each exercise that needs them so we could easily join them together for a comprehensive list and then students would also see what packages need to be used.

**Comment by JeremyZoss** [comment]
I agree with Josh.  This should be handled with an update to the setup/check scripts.  We can add an issue to track Josh's suggestion to more explicitly define the dependencies for each individual exercise, then probably close this issue.

**Comment by JeremyZoss** [comment]
Added referenced dependencies (`ros-foxy-joint-state-publisher-gui` and `ros-foxy-xacro`) to setup script in #361.  Exercise 3.3 `controllers.yaml` updated in #356.  This PR is no longer needed.

**Pull request closed without merging**
