### PR TITLE
Make changes to work with Read The Docs

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@marip8 Here is the documents generated on [ReadTheDocs](https://industrial-training.readthedocs.io/en/kinetic/).

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: did you guys have a specific reason for wanting to host the documentation on rtd?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn The main reason is because of the web hooks for updating the documentation when a commit is made.

**Comment by Levi-Armstrong** [comment]
@marip8 Friendly Reminder.

**Pull request merged**
